<?php

declare(strict_types=1);
namespace Koravik\Platform\Experience;

use Koravik\Platform\Database\Database;
use Koravik\Platform\Security\Security;
use RuntimeException;

final class ChronicleManagementController
{
    public function __construct(private readonly Database $database) {}
    public function handle(string $method,string $path): bool
    {
        if(!str_starts_with($path,'/chronicle'))return false;$account=Security::account();if(!$account)return false;$a=(string)$account['id'];$s=new ChronicleManagementService($this->database);
        if($method==='GET'&&$path==='/chronicle/new'){$this->form();return true;}
        if($method==='POST'&&$path==='/chronicle/entries'){$this->csrf();try{$id=$s->create($a,$_POST);header('Location: /chronicle/entries/'.$id,true,303);}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();header('Location: /chronicle/new',true,303);}return true;}
        if($method==='GET'&&$path==='/chronicle/search'){$this->search($s->search($a,$_GET));return true;}
        if($method==='GET'&&$path==='/chronicle/proposals'){$this->proposals($s->reflectionProposals($a));return true;}
        if($method==='POST'&&$path==='/chronicle/proposals'){$this->csrf();try{$s->proposeFromSource($a,$_POST);$_SESSION['flash']='Reflection proposal created from source context.';}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();}header('Location: /chronicle/proposals',true,303);return true;}
        if($method==='POST'&&preg_match('#^/chronicle/proposals/([a-f0-9-]{36})/(save|dismiss)$#',$path,$m)){$this->csrf();try{if($m[2]==='save'){$id=$s->saveReflectionProposal($a,$m[1],$_POST);$_SESSION['flash']='Reflection saved to Chronicle.';header('Location: /chronicle/entries/'.$id,true,303);return true;}$s->dismissReflectionProposal($a,$m[1]);$_SESSION['flash']='Reflection proposal dismissed.';}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();}header('Location: /chronicle/proposals',true,303);return true;}
        if($method==='GET'&&$path==='/chronicle/archived'){$this->list($s->list($a,true),true);return true;}
        if(preg_match('#^/chronicle/entries/([a-f0-9-]{36})$#',$path,$m)){if($method==='GET'){$this->detail($s->get($a,$m[1]));return true;}if($method==='POST'){$this->csrf();try{$s->update($a,$m[1],$_POST);$_SESSION['flash']='Chronicle entry updated.';}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();}header('Location: '.$path,true,303);return true;}}
        if($method==='POST'&&preg_match('#^/chronicle/entries/([a-f0-9-]{36})/(archive|restore|delete)$#',$path,$m)){$this->csrf();try{$s->lifecycle($a,$m[1],$m[2]);$_SESSION['flash']='Chronicle entry '.$m[2].'d.';}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();}header('Location: /chronicle',true,303);return true;}
        if($method==='GET'&&$path==='/chronicle/manage'){$this->list($s->list($a),false);return true;}
        return false;
    }
    private function form(): void {$context=(string)($_GET['context']??'');$fromHome=str_starts_with($context,'healing_home');$title=(string)($_GET['title']??'');$tags=(string)($_GET['tags']??'');$body=(string)($_GET['body']??'');$started=$fromHome?'Started from Healing Home · Journal Table context':'Started from '.self::e(str_replace('_',' ',$context));$contextPanel=$fromHome||$context!==''?'<section class="trust-panel chronicle-from-anywhere-reflection-bridge decision-consequence-preview"><p class="eyebrow">Chronicle-from-Anywhere Reflection Bridge</p><h2>Review before saving to Chronicle.</h2><p>'.$started.'. Chronicle owns the saved entry, validation, privacy, archive, and deletion behavior. What changes: submitting creates a Chronicle-owned entry. What does not: the source record remains untouched. Who owns the result: Chronicle owns saved prose, privacy, archive, and deletion behavior.</p><p><a href="/source-review">Open Source Inbox</a></p></section>':'';$this->render('New Chronicle entry',$this->flash().'<section class="page-heading"><div><p class="eyebrow">Chronicle</p><h1>Write something worth keeping.</h1><p>Private by default and owned by Chronicle.</p></div></section>'.$contextPanel.'<form class="panel" method="post" action="/chronicle/entries"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><label>Title<input name="title" maxlength="180" value="'.self::e($title).'" required></label><label>Reflection<textarea name="body" maxlength="8000" required>'.self::e($body).'</textarea></label><label>Tags, separated by commas<input name="tags" maxlength="300" value="'.self::e($tags).'"></label><button class="button">Save to Chronicle</button></form>');}
    private function list(array $rows,bool $archived): void {$cards='';foreach($rows as $r)$cards.='<article class="chronicle-entry"><p class="eyebrow">'.self::e((string)$r['provenance_label']).'</p><h2>'.self::e((string)$r['title']).'</h2><p>'.self::e(mb_strimwidth((string)$r['body'],0,240,'…')).'</p><a href="/chronicle/entries/'.self::e((string)$r['id']).'">Open entry</a></article>';$this->render('Chronicle',$this->flash().'<section class="page-heading"><div><p class="eyebrow">Chronicle</p><h1>'.($archived?'Archived entries':'Your Chronicle entries').'</h1></div><div><a class="button" href="/chronicle/new">New entry</a> <a href="/chronicle/archived">Archived</a></div></section><div class="chronicle-list">'.($cards?:'<article class="empty-state"><h2>No entries here.</h2></article>').'</div>');}
    private function proposals(array $rows): void {$cards='';foreach($rows as $r){$id=self::e((string)$r['id']);$editable=$r['status']==='proposed';$cards.='<article class="chronicle-entry proposed-reflection-review"><p class="eyebrow">'.self::e((string)$r['source_module']).' · '.self::e((string)$r['status']).'</p><form method="post" action="/chronicle/proposals/'.$id.'/save"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><label>Title<input name="title" maxlength="180" value="'.self::e((string)$r['title']).'"'.($editable?'':' disabled').'></label><label>Reflection<textarea name="body" maxlength="8000"'.($editable?'':' disabled').'>'.self::e((string)$r['body']).'</textarea></label><label>Privacy<select name="privacy"'.($editable?'':' disabled').'><option value="private">Private</option><option value="unlisted">Unlisted</option></select></label>'.($editable?'<div class="inline-actions"><button class="button">Save intentionally to Chronicle</button></form><form method="post" action="/chronicle/proposals/'.$id.'/dismiss"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><button class="quiet-button">Dismiss proposal</button></form></div>':'</form><p class="meta">Resolved proposal.</p>').'</article>';}$sourceForm='<section class="surface chronicle-reflection-proposal-sources chronicle-memory-weaving"><h2>Chronicle reflection proposal sources</h2><p>Create a proposal from Quest completion, Gather follow-up, Companion, or Healing Home Journal context. Saving still requires explicit review. Chronicle Memory Weaving improves titles, tags, source context, post-save navigation, and keeps Moment-to-Chronicle proposals editable before they become saved prose.</p><form method="post" action="/chronicle/proposals" class="form-grid"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><label>Source<select name="source_module"><option>Quest completion</option><option>Gather follow-up</option><option>Companion</option><option>Healing Home Journal</option></select></label><label>Source reference<input name="source_reference"></label><label>Title<input name="title" maxlength="180" required></label><label class="full">Draft reflection<textarea name="body" maxlength="8000" required></textarea></label><button class="button secondary">Create proposal for review</button></form></section>';$this->render('Reflection proposals',$this->flash().'<section class="page-heading"><div><p class="eyebrow">Proposed reflection review</p><h1>Should this become part of Chronicle?</h1><p>Edit the draft, choose privacy, save intentionally, or dismiss. Fictional narration and personal reflection stay distinct.</p></div><a href="/chronicle/manage">All entries</a></section>'.$sourceForm.'<div class="chronicle-list">'.($cards?:'<article class="empty-state"><h2>No reflection proposals.</h2></article>').'</div>');}
    private function search(array $rows): void {$cards='';foreach($rows as $r)$cards.='<article class="chronicle-entry"><p class="eyebrow">'.self::e((string)$r['entry_type']).' · '.self::e((string)$r['provenance_label']).'</p><h2>'.self::e((string)$r['title']).'</h2><p>'.self::e(mb_strimwidth((string)$r['body'],0,220,'…')).'</p><a href="/chronicle/entries/'.self::e((string)$r['id']).'">Open entry</a></article>';$this->render('Chronicle search',$this->flash().'<section class="page-heading chronicle-entry-search-filters"><div><p class="eyebrow">Chronicle entry search + filters</p><h1>Find saved memory without turning it into a feed.</h1><p>Search title, body, tags, type, status, date, and source/provenance while Chronicle remains the record owner.</p></div><a href="/chronicle/manage">Manage Chronicle</a></section><form class="panel" method="get" action="/chronicle/search"><label>Search<input name="q" value="'.self::e((string)($_GET['q']??'')).'"></label><label>Status<select name="status"><option value="active">Active</option><option value="archived">Archived</option></select></label><label>Type<input name="entry_type" value="'.self::e((string)($_GET['entry_type']??'')).'"></label><label>Tag<input name="tag" value="'.self::e((string)($_GET['tag']??'')).'"></label><button class="button">Search Chronicle</button></form><div class="chronicle-list">'.($cards?:'<article class="empty-state"><h2>No matching entries.</h2></article>').'</div>');}
    private function detail(array $e): void {$tags=implode(', ',(array)$e['tags']);$id=self::e((string)$e['id']);$edit=(bool)$e['editable']?'<form class="panel chronicle-editor" method="post" action="/chronicle/entries/'.$id.'"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><label>Title<input name="title" maxlength="180" value="'.self::e((string)$e['title']).'" required></label><label>Reflection<textarea name="body" maxlength="8000" required>'.self::e((string)$e['body']).'</textarea></label><label>Tags<input name="tags" maxlength="300" value="'.self::e($tags).'"></label><button class="button">Save changes</button></form>':'<section class="panel"><p>'.nl2br(self::e((string)$e['body'])).'</p><p class="meta">This generated historical entry is read-only. Its source owner controls correction or reversal.</p></section>';$lifecycle=(string)$e['status']==='archived'?'restore':'archive';$actions='<section class="chronicle-lifecycle"><h2>Entry lifecycle</h2><p>Archiving is reversible. Deletion removes this editable entry from Chronicle and cannot be undone here.</p><div class="inline-actions"><form method="post" action="/chronicle/entries/'.$id.'/'.$lifecycle.'"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><button class="quiet-button">'.ucfirst($lifecycle).'</button></form>'.((bool)$e['editable']?'<form method="post" action="/chronicle/entries/'.$id.'/delete" onsubmit="return confirm(\'Delete this Chronicle entry? This cannot be undone here.\')"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><button class="quiet-button">Delete permanently</button></form>':'').'</div></section>';$provenance='<aside class="chronicle-provenance"><p class="eyebrow">Ownership and privacy</p><h2>Private Chronicle record</h2><dl><div><dt>Source</dt><dd>'.self::e((string)$e['provenance_label']).'</dd></div><div><dt>Provenance type</dt><dd>'.self::e(str_replace('_',' ',(string)$e['provenance_type'])).'</dd></div><div><dt>Editing</dt><dd>'.((bool)$e['editable']?'You may correct this entry.':'Controlled by its source record.').'</dd></div></dl><p>Worlds and Companion do not receive this prose without a separate explicit contract.</p></aside>';$this->render((string)$e['title'],$this->flash().'<section class="page-heading"><div><p class="eyebrow">'.self::e((string)$e['provenance_label']).'</p><h1>'.self::e((string)$e['title']).'</h1><p>Created '.self::e((string)$e['created_at']).' UTC · '.self::e(ucfirst((string)$e['status'])).'</p></div><a href="/chronicle/manage">All entries</a></section><div class="chronicle-detail-layout"><div>'.$edit.$actions.'</div>'.$provenance.'</div>');}
    private function csrf(): void {if(!Security::verifyCsrf(isset($_POST['csrf'])?(string)$_POST['csrf']:null))throw new RuntimeException('Your session changed. Please try again.');}
    private function flash(): string{$f=isset($_SESSION['flash'])?(string)$_SESSION['flash']:'';unset($_SESSION['flash']);return $f?'<div class="notice" role="status">'.self::e($f).'</div>':'';}
    private function render(string $title,string $body): void {echo '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.self::e($title).' · Koravik</title><link rel="stylesheet" href="/assets/app.css"><link rel="stylesheet" href="/assets/chronicle-management.css"></head><body><main class="page">'.$body.'</main></body></html>';}
    private static function e(string $v): string{return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
}
