<?php

declare(strict_types=1);

namespace Koravik\Districts\Gather;

use Koravik\Platform\Database\Database;
use Koravik\Platform\Security\Security;
use RuntimeException;

final class GatherController
{
    public function __construct(private readonly Database $database) {}

    public function handle(string $method,string $path): bool
    {
        if((new GatherOperationsController($this->database))->handle($method,$path))return true;
        if($method==='GET'&&$path==='/gather'){$this->index();return true;}
        if($method==='POST'&&$path==='/gather/events'){$this->createEvent();return true;}
        if($method==='GET'&&preg_match('#^/gather/events/([a-f0-9-]{36})$#',$path,$m)){$this->event($m[1]);return true;}
        if($method==='POST'&&preg_match('#^/gather/events/([a-f0-9-]{36})/guest-rsvp$#',$path,$m)){$this->guestRsvp($m[1]);return true;}
        if($method==='POST'&&$path==='/gather/rsvp/lookup'){$this->lookup();return true;}
        if($method==='GET'&&preg_match('#^/gather/rsvp/manage/([A-Za-z0-9_-]+)$#',$path,$m)){$this->manage($m[1]);return true;}
        if($method==='POST'&&preg_match('#^/gather/rsvp/manage/([A-Za-z0-9_-]+)$#',$path,$m)){$this->updateManaged($m[1]);return true;}
        if($method==='POST'&&preg_match('#^/gather/events/([a-f0-9-]{36})/slots$#',$path,$m)){$this->slot($m[1]);return true;}
        if($method==='POST'&&preg_match('#^/gather/slots/([a-f0-9-]{36})/claim$#',$path,$m)){$this->claim($m[1]);return true;}
        return false;
    }

    private function index(): void
    {
        $a=Security::requireAccount();$events=(new GatherService($this->database))->dashboard((string)$a['id']);$cards='';foreach($events as $e){$cards.='<article class="surface"><p class="eyebrow">'.self::e(ucfirst((string)$e['status'])).'</p><h2>'.self::e((string)$e['title']).'</h2><p>'.self::e((string)$e['starts_at']).' UTC</p><p>'.self::e((string)($e['venue']??'')).'</p><p><a class="button" href="/gather/events/'.self::e((string)$e['id']).'/command">Command center</a> <a class="button secondary" href="/gather/events/'.self::e((string)$e['id']).'">Event view</a></p></article>';}
        $body='<section class="page-heading"><div><p class="eyebrow">Gather</p><h1>Plan the whole event in one place.</h1><p>Guest registration, RSVPs, shifts, potluck items, waitlists, attendance, and communications orbit the event.</p></div></section><section class="surface"><h2>Create an event</h2><form method="post" action="/gather/events" class="form-grid"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><label>Title<input name="title" maxlength="180" required></label><label>Starts<input name="starts_at" type="datetime-local" required></label><label>Ends<input name="ends_at" type="datetime-local"></label><label>Venue<input name="venue"></label><label>Event capacity<input name="capacity" type="number" min="1"></label><label>Visibility<select name="visibility"><option value="unlisted">Anyone with the link</option><option value="public">Public</option><option value="restricted">Restricted</option></select></label><label><input type="checkbox" name="guest_registration_enabled" checked> Allow registration without a Koravik account</label><label><input type="checkbox" name="additional_guests_enabled"> Allow additional guests</label><label>Maximum additional guests per RSVP<input name="max_additional_guests" type="number" min="0" value="0"></label><label><input type="checkbox" name="waitlist_enabled" checked> Enable event waitlist</label><label><input type="checkbox" name="automatic_waitlist_promotion"> Allow automatic promotion</label><label class="full">Description<textarea name="description"></textarea></label><button class="button" type="submit">Create event</button></form></section><section><h2>Your events</h2><div class="grid">'.($cards?:'<article class="empty-state"><h3>No events yet.</h3><p>Create one and Gather will quietly provision its Beacon sharing tools.</p></article>').'</div></section>';
        echo $this->page('Gather',$body);
    }

    private function event(string $id): void
    {
        $service=new GatherService($this->database);$account=Security::account();$e=$account?$service->event((string)$account['id'],$id):$service->publicEvent($id);if(!$e){http_response_code(404);echo $this->page('Event not found','<section class="empty-state"><h1>Event not found.</h1></section>');return;}
        $owner=$account&&((string)$account['id']===(string)$e['account_id']);$r='';if($owner)foreach($e['rsvps'] as $x){$r.='<li><strong>'.self::e((string)($x['guest_name']?:'Koravik member')).'</strong> · '.self::e(ucfirst((string)$x['response'])).' · '.(int)$x['party_size'].' person(s)</li>';}
        $slots='';foreach($e['slots'] as $s){$claims='';foreach($s['commitments'] as $c){$claims.='<li>'.self::e((string)($c['participant_name']?:'Participant')).' · '.(int)$c['quantity'].' · '.self::e((string)$c['status']).'</li>';}$claimForm='<form method="post" action="/gather/slots/'.self::e((string)$s['id']).'/claim"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><label>Name<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>Quantity<input name="quantity" type="number" min="1" value="1"></label><button class="button secondary" type="submit">Sign up</button></form>';$slots.='<article class="surface"><p class="eyebrow">'.self::e(ucfirst((string)$s['slot_type'])).'</p><h3>'.self::e((string)$s['title']).'</h3><p>'.(int)$s['quantity_claimed'].' of '.(int)$s['quantity_needed'].' claimed</p><ul>'.$claims.'</ul>'.$claimForm.'</article>';}
        $guestForm=(int)$e['guest_registration_enabled']?'<article class="surface"><h2>RSVP</h2><form method="post" action="/gather/events/'.self::e($id).'/guest-rsvp"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><label>Name<input name="guest_name" required></label><label>Email<input name="guest_email" type="email" required></label><label>Response<select name="response"><option value="yes">Yes</option><option value="maybe">Maybe</option><option value="no">No</option></select></label>'.((int)$e['additional_guests_enabled']?'<label>Additional guests<input name="additional_guests" type="number" min="0" max="'.(int)$e['max_additional_guests'].'" value="0"></label>':'').'<label>Note<input name="note"></label><button class="button" type="submit">Save RSVP</button></form><hr><form method="post" action="/gather/rsvp/lookup"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><label>Find my RSVP by email<input name="email" type="email" required></label><button class="button secondary" type="submit">Email my management link</button></form></article>':'';
        $ownerTools=$owner?'<article class="surface"><h2>Organizer tools</h2><p><a class="button" href="/gather/events/'.self::e($id).'/command">Open command center</a></p><h3>Add a planning signup</h3><form method="post" action="/gather/events/'.self::e($id).'/slots"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><label>Type<select name="type"><option value="shift">Volunteer shift</option><option value="potluck">Potluck item</option><option value="item">Needed item</option><option value="task">Planning task</option></select></label><label>Title<input name="title" required></label><label>Quantity needed<input name="quantity" type="number" min="1" value="1"></label><label><input type="checkbox" name="multiple_signups_allowed" checked> Allow multiple signups</label><label>Maximum per participant<input name="max_signups_per_participant" type="number" min="1"></label><label><input type="checkbox" name="waitlist_enabled" checked> Enable signup waitlist</label><label><input type="checkbox" name="overlapping_shifts_allowed"> Allow overlapping shifts</label><button class="button" type="submit">Add signup</button></form><h3>Responses</h3><ul>'.($r?:'<li>No responses yet.</li>').'</ul></article>':'';
        $body='<section class="page-heading"><div><p class="eyebrow">Gather event · '.self::e((string)$e['visibility']).'</p><h1>'.self::e((string)$e['title']).'</h1><p>'.self::e((string)$e['description']).'</p><p><strong>'.self::e((string)$e['starts_at']).' UTC</strong> · '.self::e((string)($e['venue']??'Location pending')).'</p></div>'.($owner?'<a href="/gather">All events</a>':'').'</section><section class="grid">'.$guestForm.$ownerTools.'</section><section><h2>Planning board</h2><div class="grid">'.($slots?:'<article class="empty-state"><h3>No signup needs yet.</h3></article>').'</div></section>';echo $this->page((string)$e['title'],$body);
    }

    private function manage(string $token):void{$r=(new GatherService($this->database))->managedRsvp($token);if(!$r){http_response_code(404);echo $this->page('RSVP link unavailable','<section class="empty-state"><h1>That RSVP link is unavailable.</h1></section>');return;}$additional=max(0,(int)$r['party_size']-1);$body='<section class="page-heading"><div><p class="eyebrow">Manage RSVP</p><h1>'.self::e((string)$r['title']).'</h1><p>'.self::e((string)$r['starts_at']).' · '.self::e((string)$r['venue']).'</p></div></section><section class="surface"><form method="post" action="/gather/rsvp/manage/'.self::e($token).'"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><label>Response<select name="response"><option value="yes"'.($r['response']==='yes'?' selected':'').'>Yes</option><option value="maybe"'.($r['response']==='maybe'?' selected':'').'>Maybe</option><option value="no"'.($r['response']==='no'?' selected':'').'>No</option></select></label>'.((int)$r['additional_guests_enabled']?'<label>Additional guests<input name="additional_guests" type="number" min="0" max="'.(int)$r['max_additional_guests'].'" value="'.$additional.'"></label>':'').'<label>Note<input name="note" value="'.self::e((string)$r['note']).'"></label><button class="button" type="submit">Update RSVP</button></form></section>';echo $this->page('Manage RSVP',$body);}
    private function createEvent():void{$this->csrf();$a=Security::requireAccount();try{$id=(new GatherService($this->database))->createEvent((string)$a['id'],$_POST);$_SESSION['flash']='Event created with Beacon sharing tools.';$this->go('/gather/events/'.$id);}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();$this->go('/gather');}}
    private function guestRsvp(string $id):void{$this->csrf();try{$token=(new GatherService($this->database))->registerGuest($id,$_POST);$_SESSION['flash']='Your RSVP was saved. A management-link delivery has been queued.';$this->go('/gather/rsvp/manage/'.$token);}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();$this->go('/gather/events/'.$id);}}
    private function lookup():void{$this->csrf();(new GatherService($this->database))->requestManagementLinks((string)($_POST['email']??''));$_SESSION['flash']='If that email is associated with an RSVP, a management link has been queued for delivery.';$this->go('/gather');}
    private function updateManaged(string $token):void{$this->csrf();try{(new GatherService($this->database))->updateManagedRsvp($token,$_POST);$_SESSION['flash']='RSVP updated.';}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();}$this->go('/gather/rsvp/manage/'.$token);}
    private function slot(string $id):void{$this->csrf();$a=Security::requireAccount();try{(new GatherService($this->database))->addSlot((string)$a['id'],$id,(string)($_POST['type']??''),(string)($_POST['title']??''),(int)($_POST['quantity']??1),$_POST);$_SESSION['flash']='Planning signup added.';}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();}$this->go('/gather/events/'.$id);}
    private function claim(string $slotId):void{$this->csrf();$a=Security::account();try{$status=(new GatherService($this->database))->claimSlot($slotId,['account_id'=>$a['id']??null,'name'=>$_POST['name']??($a['display_name']??null),'email'=>$_POST['email']??($a['email']??null)],(int)($_POST['quantity']??1));$_SESSION['flash']=$status==='waitlist'?'That signup is full; you joined its waitlist.':'Signup confirmed.';}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();}$this->go('/gather');}
    private function csrf():void{if(!Security::verifyCsrf((string)($_POST['csrf']??'')))throw new RuntimeException('Your session token expired.');}
    private function go(string $to):never{header('Location: '.$to,true,303);exit;}
    private function page(string $title,string $body):string{$flash='';if(isset($_SESSION['flash'])){$flash='<div class="notice">'.self::e((string)$_SESSION['flash']).'</div>';unset($_SESSION['flash']);}return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.self::e($title).' · Koravik</title><link rel="stylesheet" href="/assets/app.css"><link rel="stylesheet" href="/assets/journey.css"></head><body><main id="main" class="page">'.$flash.$body.'</main><footer>Koravik · Gather</footer></body></html>';}
    private static function e(string $v):string{return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
}
