<?php

declare(strict_types=1);
namespace Koravik\Districts\Gather;
use Koravik\Platform\Database\Database;
use PDO;
use RuntimeException;
final class GatherCommandService
{
    public function __construct(private readonly Database $database) {}
    public function dashboard(string $ownerId,string $eventId):array
    {
        $event=$this->ownedEvent($ownerId,$eventId);$pdo=$this->database->pdo();$event['confirmed']=$this->scalar($pdo,'SELECT COALESCE(SUM(party_size),0) FROM gather_rsvps WHERE event_id=:id AND status="active" AND response="yes"',$eventId);$event['waitlisted']=$this->scalar($pdo,'SELECT COALESCE(SUM(party_size),0) FROM gather_rsvps WHERE event_id=:id AND status="active" AND response="waitlist"',$eventId);$event['checked_in']=$this->scalar($pdo,'SELECT COALESCE(SUM(party_count),0) FROM gather_checkins WHERE event_id=:id AND corrected_at IS NULL',$eventId);$event['open_signup_units']=$this->scalar($pdo,'SELECT COALESCE(SUM(GREATEST(quantity_needed-quantity_claimed,0)),0) FROM gather_signup_slots WHERE event_id=:id',$eventId);$event['rsvps']=$this->rows($pdo,'SELECT r.*,c.party_count AS checked_in_party_count,c.checked_in_at,c.source AS checkin_source FROM gather_rsvps r LEFT JOIN gather_checkins c ON c.event_id=r.event_id AND c.rsvp_id=r.id AND c.corrected_at IS NULL WHERE r.event_id=:id ORDER BY FIELD(r.response,"yes","maybe","waitlist","no"),r.created_at',$eventId);$event['slots']=$this->rows($pdo,'SELECT * FROM gather_signup_slots WHERE event_id=:id ORDER BY FIELD(COALESCE(category_key,slot_type),"food","shift","equipment","supplies","setup","cleanup","transport","childcare","accessibility","other"),slot_type,title',$eventId);$event['mail']=$this->rows($pdo,'SELECT id,recipient_email,subject,status,attempts,failure_reason,created_at,sent_at FROM platform_mail_deliveries WHERE event_id=:id ORDER BY created_at DESC LIMIT 30',$eventId);$event['announcements']=$this->rows($pdo,'SELECT audience,title,message,urgency,email_enabled,created_at FROM gather_announcements WHERE event_id=:id ORDER BY created_at DESC LIMIT 20',$eventId);return $event;
    }
    public function updateSettings(string $ownerId,string $eventId,array $input):void
    {
        $this->ownedEvent($ownerId,$eventId);$visibility=in_array(($input['visibility']??''),['unlisted','public','restricted'],true)?$input['visibility']:'unlisted';$additional=isset($input['additional_guests_enabled']);$this->database->pdo()->prepare('UPDATE gather_events SET visibility=:visibility,capacity=:capacity,guest_registration_enabled=:guest,additional_guests_enabled=:additional,max_additional_guests=:max_guests,waitlist_enabled=:waitlist,automatic_waitlist_promotion=:auto,max_signups_per_participant=:max_signups,waitlist_offer_minutes=:offer,organizer_reply_to_email=:reply,updated_at=UTC_TIMESTAMP() WHERE id=:id')->execute(['visibility'=>$visibility,'capacity'=>($input['capacity']??'')!==''?max(1,(int)$input['capacity']):null,'guest'=>isset($input['guest_registration_enabled'])?1:0,'additional'=>$additional?1:0,'max_guests'=>$additional?max(0,(int)($input['max_additional_guests']??0)):0,'waitlist'=>isset($input['waitlist_enabled'])?1:0,'auto'=>isset($input['automatic_waitlist_promotion'])?1:0,'max_signups'=>($input['max_signups_per_participant']??'')!==''?max(1,(int)$input['max_signups_per_participant']):null,'offer'=>max(15,(int)($input['waitlist_offer_minutes']??1440)),'reply'=>filter_var(($input['organizer_reply_to_email']??''),FILTER_VALIDATE_EMAIL)?:null,'id'=>$eventId]);
    }
    public function updateDetails(string $ownerId,string $eventId,array $input):void
    {
        $this->ownedEvent($ownerId,$eventId);$title=trim((string)($input['title']??''));if($title==='')throw new RuntimeException('Give the event a title.');$starts=$this->dt((string)($input['starts_at']??''));if($starts===null)throw new RuntimeException('Choose a start time.');$accent=$this->accent((string)($input['event_accent_color']??''));$style=in_array(($input['event_header_style']??''),['classic','forest','gold','navy','custom'],true)?(string)$input['event_header_style']:'classic';$this->database->pdo()->prepare('UPDATE gather_events SET title=:title,description=:description,venue=:venue,starts_at=:starts,ends_at=:ends,event_accent_color=:accent,event_header_style=:style,updated_at=UTC_TIMESTAMP() WHERE id=:id')->execute(['title'=>$title,'description'=>(string)($input['description']??''),'venue'=>(string)($input['venue']??''),'starts'=>$starts,'ends'=>$this->dt((string)($input['ends_at']??'')),'accent'=>$accent,'style'=>$style,'id'=>$eventId]);
    }
    public function updateSlot(string $ownerId,string $eventId,string $slotId,array $input):void
    {
        $this->ownedEvent($ownerId,$eventId);$this->slotForEvent($eventId,$slotId);$type=(string)($input['type']??'');if(!in_array($type,['shift','potluck','item','task'],true))throw new RuntimeException('Choose a valid signup type.');$title=trim((string)($input['title']??''));if($title==='')throw new RuntimeException('Give the signup a title.');$quantity=max(1,(int)($input['quantity']??1));$claimed=$this->scalar($this->database->pdo(),'SELECT COALESCE(SUM(quantity),0) FROM gather_signup_commitments WHERE slot_id=:id AND status="active"',$slotId);if($quantity<$claimed)throw new RuntimeException('Quantity needed cannot be below active assigned quantity.');$this->database->pdo()->prepare('UPDATE gather_signup_slots SET slot_type=:type,category_key=:category,title=:title,description=:description,starts_at=:starts,ends_at=:ends,quantity_needed=:quantity,multiple_signups_allowed=:multiple,max_signups_per_participant=:maximum,waitlist_enabled=:waitlist,overlapping_shifts_allowed=:overlap,max_quantity_per_commitment=:max_quantity,require_attending_rsvp=:require_rsvp,updated_at=UTC_TIMESTAMP() WHERE id=:id AND event_id=:event')->execute(['type'=>$type,'category'=>$this->categoryKey((string)($input['category_key']??$type)),'title'=>$title,'description'=>trim((string)($input['description']??''))?:null,'starts'=>$this->dt((string)($input['starts_at']??'')),'ends'=>$this->dt((string)($input['ends_at']??'')),'quantity'=>$quantity,'multiple'=>isset($input['multiple_signups_allowed'])?1:0,'maximum'=>($input['max_signups_per_participant']??'')!==''?max(1,(int)$input['max_signups_per_participant']):null,'waitlist'=>isset($input['waitlist_enabled'])?1:0,'overlap'=>isset($input['overlapping_shifts_allowed'])?1:0,'max_quantity'=>($input['max_quantity_per_commitment']??'')!==''?max(1,(int)$input['max_quantity_per_commitment']):null,'require_rsvp'=>1,'id'=>$slotId,'event'=>$eventId]);
    }
    public function deleteSlot(string $ownerId,string $eventId,string $slotId):void
    {
        $this->ownedEvent($ownerId,$eventId);$this->slotForEvent($eventId,$slotId);$this->database->transaction(function(PDO $pdo)use($slotId):void{$pdo->prepare('DELETE FROM gather_signup_commitments WHERE slot_id=:id')->execute(['id'=>$slotId]);$pdo->prepare('DELETE FROM gather_signup_slots WHERE id=:id')->execute(['id'=>$slotId]);});
    }
    public function assignSlot(string $ownerId,string $eventId,string $slotId,string $rsvpId,int $quantity):string
    {
        $this->ownedEvent($ownerId,$eventId);$slot=$this->slotForEvent($eventId,$slotId);$r=$this->database->pdo()->prepare('SELECT * FROM gather_rsvps WHERE id=:id AND event_id=:event AND status="active"');$r->execute(['id'=>$rsvpId,'event'=>$eventId]);$rsvp=$r->fetch();if(!$rsvp)throw new RuntimeException('Choose an active RSVP to assign.');return (new GatherWorkflowService($this->database))->claimSlot($slotId,$rsvpId,min(max(1,$quantity),(int)$slot['quantity_needed']));
    }
    private function ownedEvent(string $ownerId,string $eventId):array{return (new GatherAuthorization($this->database))->requireManage($ownerId,$eventId);}
    private function slotForEvent(string $eventId,string $slotId):array{$s=$this->database->pdo()->prepare('SELECT * FROM gather_signup_slots WHERE id=:id AND event_id=:event LIMIT 1');$s->execute(['id'=>$slotId,'event'=>$eventId]);$slot=$s->fetch();if(!$slot)throw new RuntimeException('Signup not found.');return $slot;}
    private function dt(string $value):?string{$value=trim($value);return $value!==''?str_replace('T',' ',$value):null;}
    private function categoryKey(string $value):string{$key=preg_replace('/[^a-z0-9_]+/','_',strtolower(trim($value)))?:'other';return in_array($key,['food','shift','equipment','supplies','setup','cleanup','transport','childcare','accessibility','other','potluck','item','task'],true)?match($key){'potluck'=>'food','item'=>'supplies','task'=>'other',default=>$key}:$key;}
    private function accent(string $value):?string{$value=trim($value);return preg_match('/^#[0-9a-fA-F]{6}$/',$value)?strtoupper($value):null;}
    private function scalar(PDO $pdo,string $sql,string $id):int{$s=$pdo->prepare($sql);$s->execute(['id'=>$id]);return (int)$s->fetchColumn();}
    private function rows(PDO $pdo,string $sql,string $id):array{$s=$pdo->prepare($sql);$s->execute(['id'=>$id]);return $s->fetchAll();}
}
