<?php

declare(strict_types=1);

namespace Koravik\Districts\Health;

use Koravik\Platform\Database\Database;
use PDO;
use RuntimeException;

final class HealthService
{
    private const FEELINGS=['calm','strained','hopeful','tired','steady'];
    public function __construct(private readonly Database $database) {}

    public function history(string $accountId):array{$s=$this->database->pdo()->prepare('SELECT id,observed_on,energy_level,feeling_word,private_note,share_derived_fact,created_at,updated_at FROM health_wellbeing_checkins WHERE account_id=:account_id ORDER BY observed_on DESC LIMIT 90');$s->execute(['account_id'=>$accountId]);return $s->fetchAll();}
    public function trends(string $accountId):array{$s=$this->database->pdo()->prepare('SELECT COUNT(*) entries,ROUND(AVG(energy_level),1) avg_energy,MIN(observed_on) first_day,MAX(observed_on) last_day,SUM(share_derived_fact=1) shared_count FROM health_wellbeing_checkins WHERE account_id=:account_id AND observed_on>=DATE_SUB(CURDATE(),INTERVAL 30 DAY)');$s->execute(['account_id'=>$accountId]);$row=$s->fetch()?:[];$bands=$this->database->pdo()->prepare('SELECT CASE WHEN energy_level<=2 THEN "low" WHEN energy_level>=4 THEN "full" ELSE "steady" END band,COUNT(*) count FROM health_wellbeing_checkins WHERE account_id=:account_id AND observed_on>=DATE_SUB(CURDATE(),INTERVAL 30 DAY) GROUP BY band ORDER BY count DESC');$bands->execute(['account_id'=>$accountId]);$row['bands']=$bands->fetchAll();return $row;}
    public function hearthSignal(string $accountId): array
    {
        $t=$this->trends($accountId);$entries=(int)($t['entries']??0);$avg=$t['avg_energy']??null;$band='not enough private Health records yet';if($entries>0){$band=(float)$avg<=2.5?'lower-energy stretch':((float)$avg>=3.8?'fuller-energy stretch':'steady-energy stretch');}
        return ['entries'=>$entries,'band'=>$band,'summary'=>$entries>0?'Private Health summary: '.$band.' across '.$entries.' recent check-in(s). No feeling words or private notes leave Health.':'No private Health summary yet.'];
    }
    public function get(string $accountId,string $id):array{$s=$this->database->pdo()->prepare('SELECT * FROM health_wellbeing_checkins WHERE id=:id AND account_id=:account_id LIMIT 1');$s->execute(['id'=>$id,'account_id'=>$accountId]);$row=$s->fetch();if(!$row)throw new RuntimeException('That wellbeing check-in is unavailable.');$r=$this->database->pdo()->prepare('SELECT action,snapshot_json,created_at FROM health_checkin_revisions WHERE checkin_id=:id AND account_id=:account_id ORDER BY created_at DESC LIMIT 20');$r->execute(['id'=>$id,'account_id'=>$accountId]);$row['revisions']=$r->fetchAll();return $row;}

    public function save(string $accountId,array $input,?string $id=null):string
    {
        $date=trim((string)($input['observed_on']??''));$energy=(int)($input['energy_level']??0);$feeling=(string)($input['feeling_word']??'');$note=trim((string)($input['private_note']??''));$share=isset($input['share_derived_fact']);
        $parsed=\DateTimeImmutable::createFromFormat('!Y-m-d',$date);if(!$parsed||$parsed->format('Y-m-d')!==$date||$date>gmdate('Y-m-d'))throw new RuntimeException('Choose today or an earlier valid date.');if($energy<1||$energy>5)throw new RuntimeException('Choose an energy level from 1 to 5.');if(!in_array($feeling,self::FEELINGS,true))throw new RuntimeException('Choose one available feeling word.');if(mb_strlen($note)>1000)throw new RuntimeException('Private notes must be 1,000 characters or fewer.');$id=$id?:self::uuid();$action='created';
        $this->database->transaction(function(PDO $pdo)use($accountId,$id,$date,$energy,$feeling,$note,$share,&$action):void{$sameDay=$pdo->prepare('SELECT id FROM health_wellbeing_checkins WHERE account_id=:account_id AND observed_on=:date AND id<>:id FOR UPDATE');$sameDay->execute(['account_id'=>$accountId,'date'=>$date,'id'=>$id]);if($sameDay->fetchColumn())throw new RuntimeException('A wellbeing check-in already exists for that date. Open it from history to make a correction.');$existing=$pdo->prepare('SELECT id FROM health_wellbeing_checkins WHERE id=:id AND account_id=:account_id FOR UPDATE');$existing->execute(['id'=>$id,'account_id'=>$accountId]);if($existing->fetchColumn()){$action='corrected';$pdo->prepare('UPDATE health_wellbeing_checkins SET observed_on=:date,energy_level=:energy,feeling_word=:feeling,private_note=:note,share_derived_fact=:share,updated_at=UTC_TIMESTAMP() WHERE id=:id AND account_id=:account_id')->execute(['date'=>$date,'energy'=>$energy,'feeling'=>$feeling,'note'=>$note?:null,'share'=>$share?1:0,'id'=>$id,'account_id'=>$accountId]);}else{$pdo->prepare('INSERT INTO health_wellbeing_checkins (id,account_id,observed_on,energy_level,feeling_word,private_note,share_derived_fact,created_at,updated_at) VALUES (:id,:account_id,:date,:energy,:feeling,:note,:share,UTC_TIMESTAMP(),UTC_TIMESTAMP())')->execute(['id'=>$id,'account_id'=>$accountId,'date'=>$date,'energy'=>$energy,'feeling'=>$feeling,'note'=>$note?:null,'share'=>$share?1:0]);}$snapshot=['observed_on'=>$date,'energy_level'=>$energy,'feeling_word'=>$feeling,'share_derived_fact'=>$share];$pdo->prepare('INSERT INTO health_checkin_revisions (id,checkin_id,account_id,action,snapshot_json,created_at) VALUES (:rid,:id,:account_id,:action,:snapshot,UTC_TIMESTAMP())')->execute(['rid'=>self::uuid(),'id'=>$id,'account_id'=>$accountId,'action'=>$action,'snapshot'=>json_encode($snapshot,JSON_THROW_ON_ERROR)]);$this->audit($pdo,$accountId,'health.checkin.'.$action,$id);if($share){$band=$energy<=2?'low':($energy>=4?'full':'steady');$eventId=self::uuid();$pdo->prepare('INSERT INTO platform_outbox (id,event_name,event_version,account_id,payload_json,status,attempts,available_at,occurred_at,created_at) VALUES (:id,"Health.WellbeingCheckInRecorded",1,:account_id,:payload,"pending",0,UTC_TIMESTAMP(),UTC_TIMESTAMP(),UTC_TIMESTAMP())')->execute(['id'=>$eventId,'account_id'=>$accountId,'payload'=>json_encode(['checkin_id'=>$id,'observed_on'=>$date,'energy_band'=>$band],JSON_THROW_ON_ERROR)]);}});return $id;
    }

    public function delete(string $accountId,string $id):void{$this->database->transaction(function(PDO $pdo)use($accountId,$id):void{$row=$pdo->prepare('SELECT observed_on,energy_level,feeling_word,share_derived_fact FROM health_wellbeing_checkins WHERE id=:id AND account_id=:account_id FOR UPDATE');$row->execute(['id'=>$id,'account_id'=>$accountId]);$snapshot=$row->fetch();if(!$snapshot)throw new RuntimeException('That wellbeing check-in is unavailable.');$pdo->prepare('INSERT INTO health_checkin_revisions (id,checkin_id,account_id,action,snapshot_json,created_at) VALUES (:rid,:id,:account_id,"deleted",:snapshot,UTC_TIMESTAMP())')->execute(['rid'=>self::uuid(),'id'=>$id,'account_id'=>$accountId,'snapshot'=>json_encode($snapshot,JSON_THROW_ON_ERROR)]);$pdo->prepare('DELETE FROM health_wellbeing_checkins WHERE id=:id AND account_id=:account_id')->execute(['id'=>$id,'account_id'=>$accountId]);$this->audit($pdo,$accountId,'health.checkin.deleted',$id);});}
    private function audit(PDO $pdo,string $account,string $action,string $id):void{$pdo->prepare('INSERT INTO audit_log (id,account_id,action,subject_type,subject_id,occurred_at) VALUES (:id,:account,:action,"health_checkin",:subject,UTC_TIMESTAMP())')->execute(['id'=>self::uuid(),'account'=>$account,'action'=>$action,'subject'=>$id]);}
    private static function uuid():string{$d=random_bytes(16);$d[6]=chr((ord($d[6])&0x0f)|0x40);$d[8]=chr((ord($d[8])&0x3f)|0x80);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($d),4));}
}
