CREATE TABLE IF NOT EXISTS platform_moments (
    id CHAR(36) PRIMARY KEY,
    account_id CHAR(36) NOT NULL,
    source_module VARCHAR(80) NOT NULL,
    source_type VARCHAR(80) NOT NULL,
    source_id CHAR(36) NULL,
    moment_key VARCHAR(160) NOT NULL,
    title VARCHAR(180) NOT NULL,
    body TEXT NOT NULL,
    room_key VARCHAR(80) NULL,
    visibility ENUM('ambient','arrival','chronicle') NOT NULL DEFAULT 'ambient',
    priority ENUM('quiet','low','medium','high') NOT NULL DEFAULT 'low',
    status ENUM('queued','presented','archived','dismissed') NOT NULL DEFAULT 'queued',
    provenance_summary VARCHAR(500) NOT NULL,
    excluded_summary VARCHAR(500) NOT NULL,
    chronicle_proposal_id CHAR(36) NULL,
    created_at DATETIME NOT NULL,
    presented_at DATETIME NULL,
    archived_at DATETIME NULL,
    dismissed_at DATETIME NULL,
    UNIQUE KEY uq_platform_moment_source (account_id, source_module, source_type, source_id, moment_key),
    KEY idx_platform_moment_queue (account_id, status, visibility, priority, created_at),
    KEY idx_platform_moment_remembered (account_id, status, archived_at, presented_at, created_at),
    CONSTRAINT fk_platform_moments_account FOREIGN KEY (account_id) REFERENCES platform_accounts(id) ON DELETE CASCADE,
    CONSTRAINT fk_platform_moments_chronicle_proposal FOREIGN KEY (chronicle_proposal_id) REFERENCES chronicle_reflection_reviews(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
