<?php

declare(strict_types=1);
namespace Koravik\Platform\Companion;

use Koravik\Districts\Quests\QuestProposalExecutor;
use Koravik\Platform\Database\Database;
use Koravik\Platform\Experience\ChronicleProposalExecutor;
use Koravik\Platform\Security\Security;
use RuntimeException;

final class CompanionController
{
    public function __construct(private readonly Database $database) {}
    public function handle(string $method,string $path): bool
    {
        if(!str_starts_with($path,'/companion')) return false;$account=Security::account();if(!$account) return false;$accountId=(string)$account['id'];$service=new CompanionService($this->database);
        if($method==='GET' && $path==='/companion'){ $this->index($service->list($accountId)); return true; }
        if($method==='GET' && $path==='/companion/reflections/new'){ $this->reflectionForm(); return true; }
        if($method==='POST' && $path==='/companion/reflections'){ $this->csrf();try{$id=(new ReflectionProposalService($this->database))->create($accountId,(string)($_POST['source_context']??''),(string)($_POST['body']??''));$_SESSION['flash']='Reflection proposal created for review.';header('Location: /companion/proposals/'.$id,true,303);}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();header('Location: /companion/reflections/new',true,303);}return true; }
        if($method==='POST' && $path==='/companion/proposals'){ $this->csrf();try{$id=$service->proposeQuest($accountId,(string)($_POST['request_text']??''));$_SESSION['flash']='Proposal created for your review.';header('Location: /companion/proposals/'.$id,true,303);}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();header('Location: /companion',true,303);}return true; }
        if($method==='POST' && preg_match('#^/companion/proposals/([a-f0-9-]{36})/execute$#',$path,$m)){ $this->csrf();try{$p=$service->get($accountId,$m[1]);if($p['proposal_type']==='quest.create'){$record=(new QuestProposalExecutor($this->database))->execute($accountId,$m[1]);$_SESSION['flash']='Quest created after Quests revalidated the approved proposal.';}elseif($p['proposal_type']==='chronicle.reflection.create'){$record=(new ChronicleProposalExecutor($this->database))->execute($accountId,$m[1]);$_SESSION['flash']='Reflection saved to Chronicle after final validation.';}else throw new RuntimeException('That proposal cannot be executed.');}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();}header('Location: /companion/proposals/'.$m[1],true,303);return true; }
        if(preg_match('#^/companion/proposals/([a-f0-9-]{36})$#',$path,$m)){if($method==='GET'){ $this->detail($service->get($accountId,$m[1]));return true;}if($method==='POST'){ $this->csrf();try{$service->edit($accountId,$m[1],$_POST);$_SESSION['flash']='Proposal updated. Review the new version before approving.';}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();}header('Location: '.$path,true,303);return true;}}
        if($method==='POST' && preg_match('#^/companion/proposals/([a-f0-9-]{36})/(approve|dismiss)$#',$path,$m)){ $this->csrf();try{$service->decide($accountId,$m[1],$m[2],(int)($_POST['version']??0));$_SESSION['flash']=$m[2]==='approve'?'Proposal approved. The owning module must still execute it.':'Proposal dismissed. Nothing was changed.';}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();}header('Location: /companion/proposals/'.$m[1],true,303);return true; }
        return false;
    }
    private function index(array $rows): void
    {
        $cards='';foreach($rows as $r)$cards.='<article class="proposal-card"><p class="eyebrow">'.self::e(str_replace('_',' ',(string)$r['status'])).'</p><h2>'.self::e((string)$r['title']).'</h2><p>Owner: '.self::e((string)$r['owning_module']).' · Version '.(int)$r['version'].'</p><a href="/companion/proposals/'.self::e((string)$r['id']).'">Review proposal</a></article>';
        $body=$this->flash().'<section class="page-heading"><div><p class="eyebrow">Companion</p><h1>Ask for help without giving up the wheel.</h1><p>Companion may propose. District owners validate and execute.</p></div><a class="button secondary" href="/companion/reflections/new">Draft a reflection</a></section><section class="panel"><h2>Suggest a personal Quest</h2><form method="post" action="/companion/proposals"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><label>What feels hard or unclear?<textarea name="request_text" maxlength="1200" required></textarea></label><button class="button" type="submit">Draft a Quest proposal</button></form></section><section><h2>Recent proposals</h2><div class="grid">'.($cards?:'<article class="empty-state"><h3>No proposals yet.</h3><p>A proposal is not a saved record.</p></article>').'</div></section>';$this->render('Companion',$body);
    }
    private function reflectionForm(): void{$this->render('Draft reflection',$this->flash().'<section class="page-heading"><div><p class="eyebrow">Companion draft</p><h1>Draft a reflection before deciding where it belongs.</h1><p>Nothing is saved to Chronicle from this screen.</p></div></section><form class="panel" method="post" action="/companion/reflections"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><label>Source context<textarea name="source_context" maxlength="1000" required></textarea></label><label>Draft reflection<textarea name="body" maxlength="4000" required></textarea></label><button class="button" type="submit">Create reflection proposal</button></form>');}
    private function detail(array $p): void
    {
        $payload=$p['payload'];$reflection=$p['proposal_type']==='chronicle.reflection.create';$editable=in_array($p['status'],['awaiting_approval','draft'],true);$label=$reflection?'reflection':'Quest';$field=$reflection?'<label>Reflection title<input name="title" maxlength="180" value="'.self::e((string)$payload['title']).'" required></label><label>Reflection text<textarea name="body" maxlength="4000" required>'.self::e((string)$payload['body']).'</textarea></label>':'<label>Proposed Quest title<input name="title" maxlength="180" value="'.self::e((string)$payload['title']).'" required></label><label>Proposed notes<textarea name="notes" maxlength="4000">'.self::e((string)$payload['notes']).'</textarea></label>';
        if($editable){$actions='<form method="post" action="/companion/proposals/'.self::e((string)$p['id']).'"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'">'.$field.'<button class="button secondary" type="submit">Save edited proposal</button></form><div class="inline-actions"><form method="post" action="/companion/proposals/'.self::e((string)$p['id']).'/approve"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><input type="hidden" name="version" value="'.(int)$p['version'].'"><button class="button" type="submit">Approve this version</button></form><form method="post" action="/companion/proposals/'.self::e((string)$p['id']).'/dismiss"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><input type="hidden" name="version" value="'.(int)$p['version'].'"><button class="button secondary" type="submit">Dismiss</button></form></div>';}
        elseif($p['status']==='approved'){$button=$reflection?'Save to Chronicle':'Create Quest';$actions='<p class="notice">Approved, but not yet a saved '.$label.'. The owning module will revalidate before execution.</p><form method="post" action="/companion/proposals/'.self::e((string)$p['id']).'/execute"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><button class="button" type="submit">'.$button.'</button></form>';}
        elseif($p['status']==='executed'){$href=$p['executed_module']==='Quests'?'/quests/'.self::e((string)$p['executed_record_id']):'/chronicle';$actions='<p class="notice">Executed by '.self::e((string)$p['executed_module']).'.</p><a class="button" href="'.$href.'">Open saved record</a>';}
        else{$actions='<p class="notice">This proposal is '.self::e((string)$p['status']).'.</p>';}
        $body=$this->flash().'<section class="page-heading"><div><p class="eyebrow">Companion proposal · Version '.(int)$p['version'].'</p><h1>'.self::e((string)$p['title']).'</h1><p><span class="status">Suggestion until executed</span> Destination: '.self::e((string)$p['owning_module']).'.</p></div><a href="/companion">All proposals</a></section><div class="proposal-layout"><section class="panel"><h2>Proposed action</h2><p><strong>Owning module:</strong> '.self::e((string)$p['owning_module']).'</p><p><strong>Expected consequence:</strong> '.self::e((string)$p['consequence']).'</p>'.$actions.'</section><aside class="settings-card"><h2>Why this was suggested</h2><p>'.self::e((string)$p['reasoning']).'</p><h3>Source context</h3><p>'.self::e((string)$p['source_context']).'</p>'.($reflection?'<p class="meta">Voice: Companion-authored draft. The saved Chronicle entry becomes your approved reflection.</p>':'').'<p class="meta">Approval is specific to version '.(int)$p['version'].'.</p></aside></div>';$this->render('Review proposal',$body);
    }
    private function csrf(): void { if(!Security::verifyCsrf(isset($_POST['csrf'])?(string)$_POST['csrf']:null)) throw new RuntimeException('Your session changed. Please try again.'); }
    private function flash(): string{$f=isset($_SESSION['flash'])?(string)$_SESSION['flash']:'';unset($_SESSION['flash']);return $f!==''?'<div class="notice" role="status">'.self::e($f).'</div>':'';}
    private function render(string $title,string $body): void{echo '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.self::e($title).' · Koravik</title><link rel="stylesheet" href="/assets/app.css"></head><body><a class="skip-link" href="#main">Skip to content</a><header class="app-header"><a class="brand" href="/hearth">Koravik</a><nav aria-label="Primary"><a href="/hearth">Hearth</a><a href="/quests">Quests</a><a href="/chronicle">Chronicle</a><a href="/worlds">Worlds</a><a href="/companion" aria-current="page">Companion</a></nav></header><main id="main" class="page" tabindex="-1">'.$body.'</main><footer>Koravik helps you act, then get back to living.</footer></body></html>';}
    private static function e(string $v): string{return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
}