<?php

declare(strict_types=1);
namespace Koravik\Platform\Companion;

use Koravik\Platform\Database\Database;
use Koravik\Platform\Security\Security;
use RuntimeException;

final class CompanionContextController
{
    public function __construct(private readonly Database $database) {}
    public function handle(string $method,string $path): bool
    {
        if(!str_starts_with($path,'/companion/context')&&!str_starts_with($path,'/companion/memories')) return false;$account=Security::account();if(!$account)return false;$accountId=(string)$account['id'];$s=new CompanionContextService($this->database);
        if($method==='GET'&&$path==='/companion/context'){ $this->context($s->permissions($accountId));return true; }
        if($method==='POST'&&$path==='/companion/context'){ $this->csrf();$s->savePermissions($accountId,(array)($_POST['allowed']??[]));$_SESSION['flash']='Companion context permissions saved.';header('Location: /companion/context',true,303);return true; }
        if($method==='GET'&&$path==='/companion/memories'){ $this->memories($s->memories($accountId));return true; }
        if($method==='GET'&&preg_match('#^/companion/memories/([a-f0-9-]{36})$#',$path,$m)){ $this->memory($s->memory($accountId,$m[1]));return true; }
        if($method==='POST'&&$path==='/companion/memories'){ $this->csrf();try{$s->remember($accountId,(string)($_POST['memory_text']??''),(string)($_POST['provenance']??''));$_SESSION['flash']='Memory approved and saved.';}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();}header('Location: /companion/memories',true,303);return true; }
        if($method==='POST'&&preg_match('#^/companion/memories/([a-f0-9-]{36})$#',$path,$m)){ $this->csrf();try{$s->updateMemory($accountId,$m[1],$_POST);$_SESSION['flash']='Memory corrected.';}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();}header('Location: /companion/memories',true,303);return true; }
        if($method==='POST'&&preg_match('#^/companion/memories/([a-f0-9-]{36})/(active|disabled|deleted)$#',$path,$m)){ $this->csrf();$s->setMemoryStatus($accountId,$m[1],$m[2]);header('Location: /companion/memories',true,303);return true; }
        return false;
    }
    private function context(array $rows): void {$labels=['quest.selected'=>'Selected Quest context','chronicle.selected'=>'Selected Chronicle context','pillars.summary'=>'Pillar summaries','accessibility.preferences'=>'Accessibility preferences','companion.memory'=>'Approved Companion memory','healing_home.room_notes'=>'Healing Home room notes'];$checks='';foreach($rows as $r)$checks.='<label class="check-row"><input type="checkbox" name="allowed[]" value="'.self::e((string)$r['context_key']).'"'.((bool)$r['allowed']?' checked':'').'> '.self::e($labels[$r['context_key']]??(string)$r['context_key']).'</label>'; $this->render('Companion context',$this->flash().'<section class="page-heading companion-healing-home-context-consent"><div><p class="eyebrow">Companion permissions</p><h1>What may Companion use?</h1><p>Permissions enable only explicitly selected, minimized context. Healing Home room notes are opt-in context and do not authorize background scanning.</p></div></section><form class="panel" method="post" action="/companion/context"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'">'.$checks.'<button class="button" type="submit">Save permissions</button></form><p><a href="/companion/memories">Review Companion memories</a></p>');}
    private function memories(array $rows): void {$cards='';foreach($rows as $r){$id=self::e((string)$r['id']);$cards.='<article class="settings-card companion-memory-controls"><p class="eyebrow">'.self::e((string)$r['status']).'</p><form method="post" action="/companion/memories/'.$id.'"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><label>Memory<input name="memory_text" maxlength="500" value="'.self::e((string)$r['memory_text']).'" required></label><label>Provenance<input name="provenance" maxlength="500" value="'.self::e((string)$r['provenance']).'"></label><button class="button secondary">Correct memory</button></form><p class="meta">Created '.self::e((string)$r['created_at']).' UTC · Updated '.self::e((string)$r['updated_at']).' UTC</p><p><a href="/companion/memories/'.$id.'">Open provenance detail</a></p><div class="inline-actions"><form method="post" action="/companion/memories/'.$id.'/disabled"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><button class="quiet-button">Disable future use</button></form><form method="post" action="/companion/memories/'.$id.'/deleted"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><button class="quiet-button">Remove memory</button></form></div></article>';}$this->render('Companion memories',$this->flash().'<section class="page-heading"><div><p class="eyebrow">Companion memory controls</p><h1>Remember only what you approve.</h1><p>Review provenance, correct wording, disable future use, or remove memory. These records remain separate from Chronicle, Quests, and World State.</p></div><a href="/audit">Audit trail</a></section><form class="panel" method="post" action="/companion/memories"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><label>Memory to approve<input name="memory_text" maxlength="500" required></label><label>Provenance<input name="provenance" maxlength="500" value="Approved directly by the player."></label><button class="button">Approve memory</button></form><div class="grid">'.($cards?:'<article class="empty-state"><h2>No approved memories.</h2></article>').'</div>');}
    private function memory(array $r): void {$history='';foreach($r['history'] as $h)$history.='<li>'.self::e((string)$h['action']).' · '.self::e((string)$h['occurred_at']).' UTC</li>';$this->render('Companion memory detail','<section class="page-heading companion-memory-provenance-detail"><div><p class="eyebrow">Companion memory provenance detail</p><h1>Where did this memory come from?</h1><p>Usage boundary: active memories may be used only when Companion memory permission is enabled. Disabled or deleted memories are not used for future suggestions.</p></div><a href="/companion/memories">Back to memories</a></section><section class="surface"><h2>Memory</h2><p>'.self::e((string)$r['memory_text']).'</p><dl><div><dt>Status</dt><dd>'.self::e((string)$r['status']).'</dd></div><div><dt>Provenance</dt><dd>'.self::e((string)$r['provenance']).'</dd></div><div><dt>Created</dt><dd>'.self::e((string)$r['created_at']).' UTC</dd></div><div><dt>Updated</dt><dd>'.self::e((string)$r['updated_at']).' UTC</dd></div></dl></section><section class="surface"><h2>Status history and corrections</h2><ul>'.($history?:'<li>No audit history found.</li>').'</ul></section>');}
    private function csrf(): void {if(!Security::verifyCsrf(isset($_POST['csrf'])?(string)$_POST['csrf']:null))throw new RuntimeException('Your session changed. Please try again.');}
    private function flash(): string{$f=isset($_SESSION['flash'])?(string)$_SESSION['flash']:'';unset($_SESSION['flash']);return $f?'<div class="notice" role="status">'.self::e($f).'</div>':'';}
    private function render(string $title,string $body): void {echo '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.self::e($title).' · Koravik</title><link rel="stylesheet" href="/assets/app.css"></head><body><main class="page">'.$body.'</main></body></html>';}
    private static function e(string $v): string{return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
}
