<?php

declare(strict_types=1);

namespace Koravik\Platform\Households;

use Koravik\Districts\Gather\GatherService;
use Koravik\Districts\Quests\QuestService;
use Koravik\Platform\Database\Database;
use Koravik\Platform\Mail\MailQueue;
use Koravik\Platform\Notifications\NotificationService;
use RuntimeException;

final class HouseholdService
{
    public function __construct(private readonly Database $database) {}

    public function memberships(string $account):array{$s=$this->database->pdo()->prepare('SELECT h.*,m.role membership_role FROM household_memberships m JOIN households h ON h.id=m.household_id WHERE m.account_id=:account AND m.status="active" ORDER BY FIELD(h.status,"active","suspended","archived"),h.name');$s->execute(['account'=>$account]);return $s->fetchAll();}
    public function can(string $account,string $household,string $capability):bool{$s=$this->database->pdo()->prepare('SELECT m.role,h.status household_status FROM household_memberships m JOIN households h ON h.id=m.household_id WHERE m.household_id=:household AND m.account_id=:account AND m.status="active"');$s->execute(['household'=>$household,'account'=>$account]);$m=$s->fetch();if(!$m)return false;if($m['household_status']!=='active'&&!in_array($capability,['view','manage_household'],true))return false;$map=['view'=>['owner','admin','member'],'coordinate'=>['owner','admin','member'],'manage_resources'=>['owner','admin'],'manage_members'=>['owner','admin'],'manage_household'=>['owner']];return in_array((string)$m['role'],$map[$capability]??[],true);}

    public function create(string $account,array $input):string
    {
        $name=trim((string)($input['name']??''));if($name===''||mb_strlen($name)>180)throw new RuntimeException('Give the Household a clear name.');$id=self::uuid();$membership=self::uuid();$this->database->transaction(function($pdo)use($id,$membership,$account,$name,$input):void{$pdo->prepare('INSERT INTO households (id,name,summary,primary_timezone,status,preferences_json,created_by_account_id,created_at,updated_at) VALUES (:id,:name,:summary,:timezone,"active",:preferences,:account,UTC_TIMESTAMP(),UTC_TIMESTAMP())')->execute(['id'=>$id,'name'=>$name,'summary'=>trim((string)($input['summary']??'')),'timezone'=>trim((string)($input['timezone']??'UTC'))?:'UTC','preferences'=>json_encode(['reminders_enabled'=>true],JSON_THROW_ON_ERROR),'account'=>$account]);$pdo->prepare('INSERT INTO household_memberships (id,household_id,account_id,role,status,joined_at,created_at,updated_at) VALUES (:id,:household,:account,"owner","active",UTC_TIMESTAMP(),UTC_TIMESTAMP(),UTC_TIMESTAMP())')->execute(['id'=>$membership,'household'=>$id,'account'=>$account]);$this->activity($pdo,$id,$account,'household.created','household',$id,[]);});return $id;
    }

    public function dashboard(string $account,string $household):array
    {
        if(!$this->can($account,$household,'view'))throw new RuntimeException('Household not found.');$pdo=$this->database->pdo();$h=$pdo->prepare('SELECT h.*,m.role membership_role FROM households h JOIN household_memberships m ON m.household_id=h.id WHERE h.id=:id AND m.account_id=:account AND m.status="active"');$h->execute(['id'=>$household,'account'=>$account]);$members=$pdo->prepare('SELECT m.*,a.display_name,a.email FROM household_memberships m JOIN platform_accounts a ON a.id=m.account_id WHERE m.household_id=:id AND m.status="active" ORDER BY FIELD(m.role,"owner","admin","member"),a.display_name');$members->execute(['id'=>$household]);$resources=$pdo->prepare('SELECT * FROM household_resources WHERE household_id=:id AND status="active" ORDER BY updated_at DESC');$resources->execute(['id'=>$household]);$events=$pdo->prepare('SELECT id,title,starts_at,status FROM gather_events WHERE owner_type="household" AND household_id=:id ORDER BY starts_at DESC LIMIT 12');$events->execute(['id'=>$household]);$proposals=$pdo->prepare('SELECT p.*,a.display_name recipient_name FROM household_quest_proposals p JOIN platform_accounts a ON a.id=p.recipient_account_id WHERE p.household_id=:id ORDER BY p.created_at DESC LIMIT 20');$proposals->execute(['id'=>$household]);$mine=$pdo->prepare('SELECT * FROM household_quest_proposals WHERE household_id=:id AND recipient_account_id=:account AND status="proposed" ORDER BY created_at');$mine->execute(['id'=>$household,'account'=>$account]);$invites=$pdo->prepare('SELECT id,email,role,status,expires_at FROM household_invitations WHERE household_id=:id AND status="pending" ORDER BY created_at DESC');$invites->execute(['id'=>$household]);$activity=$pdo->prepare('SELECT * FROM household_activity WHERE household_id=:id ORDER BY created_at DESC LIMIT 20');$activity->execute(['id'=>$household]);return ['household'=>$h->fetch(),'members'=>$members->fetchAll(),'resources'=>$resources->fetchAll(),'events'=>$events->fetchAll(),'proposals'=>$proposals->fetchAll(),'mine'=>$mine->fetchAll(),'invitations'=>$invites->fetchAll(),'activity'=>$activity->fetchAll()];
    }

    public function update(string $actor,string $household,array $input):void{$this->require($actor,$household,'manage_household');$name=trim((string)($input['name']??''));if($name===''||mb_strlen($name)>180)throw new RuntimeException('Give the Household a clear name.');$prefs=['reminders_enabled'=>isset($input['reminders_enabled'])];$this->database->pdo()->prepare('UPDATE households SET name=:name,summary=:summary,primary_timezone=:timezone,preferences_json=:preferences,updated_at=UTC_TIMESTAMP() WHERE id=:id')->execute(['name'=>$name,'summary'=>trim((string)($input['summary']??'')),'timezone'=>trim((string)($input['timezone']??'UTC'))?:'UTC','preferences'=>json_encode($prefs,JSON_THROW_ON_ERROR),'id'=>$household]);$this->activity($this->database->pdo(),$household,$actor,'household.settings_updated','household',$household,[]);}
    public function lifecycle(string $actor,string $household,string $state):void{$this->require($actor,$household,'manage_household');if(!in_array($state,['active','suspended','archived'],true))throw new RuntimeException('Choose a valid Household state.');$pdo=$this->database->pdo();$s=$pdo->prepare('SELECT status FROM households WHERE id=:id');$s->execute(['id'=>$household]);$before=$s->fetchColumn();$pdo->prepare('UPDATE households SET status=:state,suspended_at=IF(:suspended="suspended",UTC_TIMESTAMP(),NULL),archived_at=IF(:archived="archived",UTC_TIMESTAMP(),NULL),updated_at=UTC_TIMESTAMP() WHERE id=:id')->execute(['state'=>$state,'suspended'=>$state,'archived'=>$state,'id'=>$household]);$pdo->prepare('INSERT INTO household_recovery_records (id,household_id,actor_account_id,previous_status,new_status,created_at) VALUES (:id,:household,:actor,:previous,:new,UTC_TIMESTAMP())')->execute(['id'=>self::uuid(),'household'=>$household,'actor'=>$actor,'previous'=>$before,'new'=>$state]);$this->activity($pdo,$household,$actor,'household.lifecycle_changed','household',$household,['previous'=>$before,'new'=>$state]);}

    public function invite(string $actor,string $household,string $email,string $role):void
    {
        $this->require($actor,$household,'manage_members');$email=strtolower(trim($email));if(!filter_var($email,FILTER_VALIDATE_EMAIL))throw new RuntimeException('Enter a valid email address.');$role=$role==='admin'?'admin':'member';$pdo=$this->database->pdo();$h=$this->dashboard($actor,$household)['household'];$raw=self::token();$id=self::uuid();$url=rtrim((string)\env('APP_URL','http://127.0.0.1:8080'),'/').'/households/invitations/'.$raw;$delivery=(new MailQueue($this->database))->enqueue('household.invitation',$email,'','Invitation to '.$h['name'],'<h1>Private Household invitation</h1><p><a href="'.self::e($url).'">Review invitation</a></p>','Review your private Household invitation: '.$url);$pdo->prepare('INSERT INTO household_invitations (id,household_id,email,role,token_hash,status,invited_by_account_id,delivery_id,expires_at,last_sent_at,created_at,updated_at) VALUES (:id,:household,:email,:role,:hash,"pending",:actor,:delivery,DATE_ADD(UTC_TIMESTAMP(),INTERVAL 14 DAY),UTC_TIMESTAMP(),UTC_TIMESTAMP(),UTC_TIMESTAMP())')->execute(['id'=>$id,'household'=>$household,'email'=>$email,'role'=>$role,'hash'=>hash('sha256',$raw),'actor'=>$actor,'delivery'=>$delivery]);$this->activity($pdo,$household,$actor,'membership.invited','invitation',$id,['email'=>$email,'delivery_id'=>$delivery]);
    }

    public function accept(string $account,string $token):string
    {
        $pdo=$this->database->pdo();$s=$pdo->prepare('SELECT i.*,a.email account_email FROM household_invitations i JOIN platform_accounts a ON a.id=:account WHERE i.token_hash=:hash AND i.status="pending" AND i.expires_at>UTC_TIMESTAMP()');$s->execute(['account'=>$account,'hash'=>hash('sha256',$token)]);$i=$s->fetch();if(!$i||strtolower((string)$i['email'])!==strtolower((string)$i['account_email']))throw new RuntimeException('That Household invitation is unavailable for this account.');$this->database->transaction(function($pdo)use($i,$account):void{$pdo->prepare('INSERT INTO household_memberships (id,household_id,account_id,role,status,invited_by_account_id,joined_at,created_at,updated_at) VALUES (:id,:household,:account,:role,"active",:inviter,UTC_TIMESTAMP(),UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE role=VALUES(role),status="active",ended_at=NULL,updated_at=UTC_TIMESTAMP()')->execute(['id'=>self::uuid(),'household'=>$i['household_id'],'account'=>$account,'role'=>$i['role'],'inviter'=>$i['invited_by_account_id']]);$pdo->prepare('UPDATE household_invitations SET status="accepted",accepted_by_account_id=:account,updated_at=UTC_TIMESTAMP() WHERE id=:id')->execute(['account'=>$account,'id'=>$i['id']]);$this->activity($pdo,(string)$i['household_id'],$account,'membership.accepted','membership',null,[]);});return (string)$i['household_id'];
    }

    public function changeRole(string $actor,string $household,string $membership,string $role):void{$this->require($actor,$household,'manage_members');if(!in_array($role,['admin','member'],true))throw new RuntimeException('Choose a valid role.');$target=$this->membershipAccount($household,$membership);$s=$this->database->pdo()->prepare('UPDATE household_memberships SET role=:role,updated_at=UTC_TIMESTAMP() WHERE id=:id AND household_id=:household AND role<>"owner" AND status="active"');$s->execute(['role'=>$role,'id'=>$membership,'household'=>$household]);if($s->rowCount()!==1)throw new RuntimeException('That membership cannot be changed.');$this->notify($target,'Household role updated','Your role in a private Household is now '.ucfirst($role).'.','/households/'.$household,'Sent because a Household administrator changed your scoped membership role.',$membership);}
    public function remove(string $actor,string $household,string $membership):void{$this->require($actor,$household,'manage_members');$target=$this->membershipAccount($household,$membership);$s=$this->database->pdo()->prepare('UPDATE household_memberships SET status="removed",ended_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE id=:id AND household_id=:household AND role<>"owner" AND status="active"');$s->execute(['id'=>$membership,'household'=>$household]);if($s->rowCount()!==1)throw new RuntimeException('That membership cannot be removed.');$this->notify($target,'Household membership ended','Your membership in a private Household was removed.','/households','Sent because a Household administrator ended your membership.',$membership);}
    public function leave(string $account,string $household):void{$s=$this->database->pdo()->prepare('UPDATE household_memberships SET status="left",ended_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE household_id=:household AND account_id=:account AND role<>"owner" AND status="active"');$s->execute(['household'=>$household,'account'=>$account]);if($s->rowCount()!==1)throw new RuntimeException('Transfer ownership before leaving this Household.');$this->activity($this->database->pdo(),$household,$account,'membership.left','membership',null,[]);}
    public function revokeInvitation(string $actor,string $household,string $invitation):void{$this->require($actor,$household,'manage_members');$s=$this->database->pdo()->prepare('UPDATE household_invitations SET status="revoked",revoked_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE id=:id AND household_id=:household AND status="pending"');$s->execute(['id'=>$invitation,'household'=>$household]);if($s->rowCount()!==1)throw new RuntimeException('That invitation is no longer pending.');$this->activity($this->database->pdo(),$household,$actor,'membership.invitation_revoked','invitation',$invitation,[]);}
    public function transfer(string $actor,string $household,string $membership):void{$this->require($actor,$household,'manage_household');$this->database->transaction(function($pdo)use($actor,$household,$membership):void{$s=$pdo->prepare('SELECT 1 FROM household_memberships WHERE id=:id AND household_id=:household AND status="active"');$s->execute(['id'=>$membership,'household'=>$household]);if(!$s->fetchColumn())throw new RuntimeException('Choose an active member.');$pdo->prepare('UPDATE household_memberships SET role="admin",updated_at=UTC_TIMESTAMP() WHERE household_id=:household AND account_id=:actor AND role="owner"')->execute(['household'=>$household,'actor'=>$actor]);$pdo->prepare('UPDATE household_memberships SET role="owner",updated_at=UTC_TIMESTAMP() WHERE id=:id')->execute(['id'=>$membership]);$this->activity($pdo,$household,$actor,'household.ownership_transferred','membership',$membership,[]);});}

    public function resource(string $actor,string $household,array $input):void{$this->require($actor,$household,'manage_resources');$title=trim((string)($input['title']??''));$type=(string)($input['resource_type']??'reference');$url=trim((string)($input['url']??''));if($title===''||mb_strlen($title)>180)throw new RuntimeException('Give the resource a clear title.');if(!in_array($type,['instruction','contact','link','reference'],true))$type='reference';if($url!==''&&!filter_var($url,FILTER_VALIDATE_URL))throw new RuntimeException('Enter a valid resource URL.');$id=self::uuid();$this->database->pdo()->prepare('INSERT INTO household_resources (id,household_id,created_by_account_id,resource_type,title,body,url,status,created_at,updated_at) VALUES (:id,:household,:actor,:type,:title,:body,:url,"active",UTC_TIMESTAMP(),UTC_TIMESTAMP())')->execute(['id'=>$id,'household'=>$household,'actor'=>$actor,'type'=>$type,'title'=>$title,'body'=>trim((string)($input['body']??'')),'url'=>$url?:null]);$this->activity($this->database->pdo(),$household,$actor,'household.resource_created','resource',$id,[]);}
    public function createEvent(string $actor,string $household,array $input):string{$this->require($actor,$household,'coordinate');$id=(new GatherService($this->database))->createEvent($actor,$input);$this->database->pdo()->prepare('UPDATE gather_events SET owner_type="household",household_id=:household,visibility="private",updated_at=UTC_TIMESTAMP() WHERE id=:id AND account_id=:actor')->execute(['household'=>$household,'id'=>$id,'actor'=>$actor]);$this->activity($this->database->pdo(),$household,$actor,'gather.event_created','gather_event',$id,[]);return $id;}

    public function proposeQuest(string $actor,string $household,array $input):void{$this->require($actor,$household,'coordinate');$recipient=(string)($input['recipient_account_id']??'');$title=trim((string)($input['title']??''));if($title===''||mb_strlen($title)>180)throw new RuntimeException('Give the responsibility a clear title.');$s=$this->database->pdo()->prepare('SELECT 1 FROM household_memberships WHERE household_id=:household AND account_id=:recipient AND status="active"');$s->execute(['household'=>$household,'recipient'=>$recipient]);if(!$s->fetchColumn())throw new RuntimeException('Choose an active Household member.');$frequency=in_array(($input['frequency']??'none'),['none','daily','weekly','monthly','yearly'],true)?$input['frequency']:'none';$id=self::uuid();$this->database->pdo()->prepare('INSERT INTO household_quest_proposals (id,household_id,proposed_by_account_id,recipient_account_id,title,description,recurrence_json,status,created_at,updated_at) VALUES (:id,:household,:actor,:recipient,:title,:description,:recurrence,"proposed",UTC_TIMESTAMP(),UTC_TIMESTAMP())')->execute(['id'=>$id,'household'=>$household,'actor'=>$actor,'recipient'=>$recipient,'title'=>$title,'description'=>trim((string)($input['description']??'')),'recurrence'=>json_encode(['frequency'=>$frequency,'interval_count'=>max(1,(int)($input['interval_count']??1)),'starts_on'=>(string)($input['starts_on']??gmdate('Y-m-d'))],JSON_THROW_ON_ERROR)]);$this->activity($this->database->pdo(),$household,$actor,'quest.proposed','quest_proposal',$id,[]);$this->notify($recipient,'Household responsibility proposed',$title.' is waiting for your choice.','/households/'.$household,'Sent because a Household member proposed a responsibility; no Quest exists until you accept.',$id);}
    public function respond(string $account,string $proposal,string $response):?string{$response=$response==='accepted'?'accepted':'declined';$s=$this->database->pdo()->prepare('SELECT * FROM household_quest_proposals WHERE id=:id AND recipient_account_id=:account AND status="proposed"');$s->execute(['id'=>$proposal,'account'=>$account]);$p=$s->fetch();if(!$p)throw new RuntimeException('That responsibility proposal is unavailable.');$quest=null;if($response==='accepted'){$options=json_decode((string)$p['recurrence_json'],true,512,JSON_THROW_ON_ERROR);$options['quest_type']=$options['frequency']==='none'?'responsibility':'habit';$options['origin_type']='personal';$options['origin_reference']=$proposal;$quest=(new QuestService($this->database))->create($account,(string)$p['title'],(string)$p['description'],$options);}$this->database->pdo()->prepare('UPDATE household_quest_proposals SET status=:status,quest_id=:quest,responded_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE id=:id')->execute(['status'=>$response,'quest'=>$quest,'id'=>$proposal]);$this->activity($this->database->pdo(),(string)$p['household_id'],$account,'quest.'.$response,'quest_proposal',$proposal,['quest_id'=>$quest]);return $quest;}

    private function require(string $account,string $household,string $capability):void{if(!$this->can($account,$household,$capability))throw new RuntimeException('You do not have that Household capability.');}
    private function membershipAccount(string $household,string $membership):string{$s=$this->database->pdo()->prepare('SELECT account_id FROM household_memberships WHERE id=:id AND household_id=:household AND role<>"owner" AND status="active"');$s->execute(['id'=>$membership,'household'=>$household]);$account=$s->fetchColumn();if(!$account)throw new RuntimeException('That membership cannot be changed.');return (string)$account;}
    private function notify(string $account,string $title,string $body,string $target,string $reason,string $source):void{(new NotificationService($this->database))->create($account,'Households','household.coordination',$title,$body,$target,$reason,$source);}
    private function activity($pdo,string $household,string $actor,string $action,string $type,?string $subject,array $context):void{$pdo->prepare('INSERT INTO household_activity (id,household_id,actor_account_id,action,subject_type,subject_id,context_json,created_at) VALUES (:id,:household,:actor,:action,:type,:subject,:context,UTC_TIMESTAMP())')->execute(['id'=>self::uuid(),'household'=>$household,'actor'=>$actor,'action'=>$action,'type'=>$type,'subject'=>$subject,'context'=>json_encode($context,JSON_THROW_ON_ERROR)]);}
    private static function token():string{return rtrim(strtr(base64_encode(random_bytes(32)),'+/','-_'),'=');}
    private static function e(string $v):string{return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
    private static function uuid():string{$d=random_bytes(16);$d[6]=chr((ord($d[6])&0x0f)|0x40);$d[8]=chr((ord($d[8])&0x3f)|0x80);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($d),4));}
}
