<?php

declare(strict_types=1);

namespace Koravik\Platform\Households;

use Koravik\Platform\Database\Database;
use Koravik\Platform\Security\Security;
use RuntimeException;

final class HouseholdController
{
    public function __construct(private readonly Database $database) {}

    public function handle(string $method,string $path):bool
    {
        if($method==='GET'&&$path==='/households'){$this->index();return true;}
        if($method==='POST'&&$path==='/households'){$this->create();return true;}
        if($method==='GET'&&preg_match('#^/households/invitations/([A-Za-z0-9_-]+)$#',$path,$m)){$this->accept($m[1]);return true;}
        if($method==='GET'&&preg_match('#^/households/([a-f0-9-]{36})$#',$path,$m)){$this->show($m[1]);return true;}
        if($method==='POST'&&preg_match('#^/households/([a-f0-9-]{36})/settings$#',$path,$m)){$this->update($m[1]);return true;}
        if($method==='POST'&&preg_match('#^/households/([a-f0-9-]{36})/lifecycle/(active|suspended|archived)$#',$path,$m)){$this->lifecycle($m[1],$m[2]);return true;}
        if($method==='POST'&&preg_match('#^/households/([a-f0-9-]{36})/invitations$#',$path,$m)){$this->invite($m[1]);return true;}
        if($method==='POST'&&preg_match('#^/households/([a-f0-9-]{36})/invitations/([a-f0-9-]{36})/revoke$#',$path,$m)){$this->revokeInvitation($m[1],$m[2]);return true;}
        if($method==='POST'&&preg_match('#^/households/([a-f0-9-]{36})/leave$#',$path,$m)){$this->leave($m[1]);return true;}
        if($method==='POST'&&preg_match('#^/households/([a-f0-9-]{36})/members/([a-f0-9-]{36})/role$#',$path,$m)){$this->role($m[1],$m[2]);return true;}
        if($method==='POST'&&preg_match('#^/households/([a-f0-9-]{36})/members/([a-f0-9-]{36})/remove$#',$path,$m)){$this->remove($m[1],$m[2]);return true;}
        if($method==='POST'&&preg_match('#^/households/([a-f0-9-]{36})/ownership/([a-f0-9-]{36})$#',$path,$m)){$this->transfer($m[1],$m[2]);return true;}
        if($method==='POST'&&preg_match('#^/households/([a-f0-9-]{36})/resources$#',$path,$m)){$this->resource($m[1]);return true;}
        if($method==='POST'&&preg_match('#^/households/([a-f0-9-]{36})/events$#',$path,$m)){$this->event($m[1]);return true;}
        if($method==='POST'&&preg_match('#^/households/([a-f0-9-]{36})/quest-proposals$#',$path,$m)){$this->propose($m[1]);return true;}
        if($method==='POST'&&preg_match('#^/households/quest-proposals/([a-f0-9-]{36})/(accepted|declined)$#',$path,$m)){$this->respond($m[1],$m[2]);return true;}
        return false;
    }

    private function index():void
    {
        $a=Security::requireAccount();$s=new HouseholdService($this->database);$cards='';foreach($s->memberships((string)$a['id']) as $h)$cards.='<article class="surface"><p class="eyebrow">'.self::e(ucfirst((string)$h['membership_role'])).' · '.self::e(ucfirst((string)$h['status'])).'</p><h2>'.self::e((string)$h['name']).'</h2><p>'.self::e((string)$h['summary']).'</p><a class="button" href="/households/'.self::e((string)$h['id']).'">Open Household</a></article>';$body='<section class="page-heading"><div><p class="eyebrow">Households</p><h1>Coordinate home life without surrendering personal ownership.</h1><p>Households are optional and private by default.</p></div></section><section class="surface"><h2>Create a Household</h2><form method="post" action="/households"><input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'"><label>Name<input name="name" required maxlength="180"></label><label>Summary<textarea name="summary"></textarea></label><label>Timezone<input name="timezone" value="America/New_York"></label><button class="button">Create Household</button></form></section><section><h2>Your Households</h2><div class="grid">'.($cards?:'<article class="empty-state"><h3>No Households yet.</h3><p>Personal Koravik remains fully available.</p></article>').'</div></section>';$this->page('Households',$body);
    }

    private function show(string $id):void
    {
        $a=Security::requireAccount();$s=new HouseholdService($this->database);try{$d=$s->dashboard((string)$a['id'],$id);}catch(RuntimeException){$this->missing();return;}$h=$d['household'];$members='';foreach($d['members'] as $m){$controls='';if($s->can((string)$a['id'],$id,'manage_members')&&$m['role']!=='owner'){$controls='<form method="post" action="/households/'.$id.'/members/'.self::e((string)$m['id']).'/role">'.$this->csrfField().'<select name="role"><option value="member">Member</option><option value="admin">Admin</option></select><button class="quiet-button">Change</button></form><form method="post" action="/households/'.$id.'/members/'.self::e((string)$m['id']).'/remove">'.$this->csrfField().'<button class="quiet-button">Remove</button></form>';if($s->can((string)$a['id'],$id,'manage_household'))$controls.='<form method="post" action="/households/'.$id.'/ownership/'.self::e((string)$m['id']).'">'.$this->csrfField().'<button class="quiet-button">Transfer ownership</button></form>';}$members.='<article class="surface"><h3>'.self::e((string)$m['display_name']).'</h3><p>'.self::e(ucfirst((string)$m['role'])).'</p>'.$controls.'</article>';}
        $resources='';foreach($d['resources'] as $r)$resources.='<article class="surface"><p class="eyebrow">'.self::e(ucfirst((string)$r['resource_type'])).'</p><h3>'.self::e((string)$r['title']).'</h3><p>'.self::e((string)$r['body']).'</p>'.($r['url']?'<a href="'.self::e((string)$r['url']).'">Open resource</a>':'').'</article>';$events='';foreach($d['events'] as $e)$events.='<li><a href="/gather/events/'.self::e((string)$e['id']).'">'.self::e((string)$e['title']).'</a> · '.self::e((string)$e['starts_at']).'</li>';$mine='';foreach($d['mine'] as $p)$mine.='<article class="surface"><h3>'.self::e((string)$p['title']).'</h3><p>'.self::e((string)$p['description']).'</p><form method="post" action="/households/quest-proposals/'.self::e((string)$p['id']).'/accepted">'.$this->csrfField().'<button class="button">Accept into my Quests</button></form><form method="post" action="/households/quest-proposals/'.self::e((string)$p['id']).'/declined">'.$this->csrfField().'<button class="button secondary">Decline</button></form></article>';
        $memberOptions='';foreach($d['members'] as $m)$memberOptions.='<option value="'.self::e((string)$m['account_id']).'">'.self::e((string)$m['display_name']).'</option>';$coord=$s->can((string)$a['id'],$id,'coordinate')?'<section class="grid"><article class="surface"><h2>Propose a responsibility</h2><p>The recipient decides whether it becomes their personal Quest.</p><form method="post" action="/households/'.$id.'/quest-proposals">'.$this->csrfField().'<label>For<select name="recipient_account_id">'.$memberOptions.'</select></label><label>Title<input name="title" required></label><label>Notes<textarea name="description"></textarea></label><label>Repeat<select name="frequency"><option value="none">One time</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><input type="hidden" name="interval_count" value="1"><input type="hidden" name="starts_on" value="'.gmdate('Y-m-d').'"><button class="button">Propose</button></form></article><article class="surface"><h2>Private Gather event</h2><form method="post" action="/households/'.$id.'/events">'.$this->csrfField().'<label>Title<input name="title" required></label><label>Starts<input type="datetime-local" name="starts_at" required></label><label>Venue<input name="venue"></label><label>Description<textarea name="description"></textarea></label><button class="button">Create private event</button></form></article></section>':'';
        $pending='';foreach($d['invitations'] as $i)$pending.='<li>'.self::e((string)$i['email']).' · '.self::e((string)$i['role']).'<form method="post" action="/households/'.$id.'/invitations/'.self::e((string)$i['id']).'/revoke">'.$this->csrfField().'<button class="quiet-button">Revoke</button></form></li>';$manage=$s->can((string)$a['id'],$id,'manage_resources')?'<section class="grid"><article class="surface"><h2>Add private resource</h2><form method="post" action="/households/'.$id.'/resources">'.$this->csrfField().'<label>Type<select name="resource_type"><option>reference</option><option>instruction</option><option>contact</option><option>link</option></select></label><label>Title<input name="title" required></label><label>Details<textarea name="body"></textarea></label><label>URL<input type="url" name="url"></label><button class="button">Add resource</button></form></article><article class="surface"><h2>Invite a member</h2><form method="post" action="/households/'.$id.'/invitations">'.$this->csrfField().'<label>Email<input type="email" name="email" required></label><label>Role<select name="role"><option value="member">Member</option><option value="admin">Admin</option></select></label><button class="button">Send private invitation</button></form><h3>Pending invitations</h3><ul>'.($pending?:'<li>No pending invitations.</li>').'</ul></article></section>':'';
        $owner=$s->can((string)$a['id'],$id,'manage_household')?'<section class="surface"><h2>Household settings and recovery</h2><form method="post" action="/households/'.$id.'/settings">'.$this->csrfField().'<label>Name<input name="name" value="'.self::e((string)$h['name']).'" required></label><label>Summary<textarea name="summary">'.self::e((string)$h['summary']).'</textarea></label><label>Timezone<input name="timezone" value="'.self::e((string)$h['primary_timezone']).'"></label><label><input type="checkbox" name="reminders_enabled" checked> Coordination reminders</label><button class="button">Save settings</button></form><p>'.implode(' ',array_map(fn($state)=>'<form style="display:inline" method="post" action="/households/'.$id.'/lifecycle/'.$state.'">'.$this->csrfField().'<button class="button secondary">'.ucfirst($state).'</button></form>',['active','suspended','archived'])).'</p></section>':'';
        $activity='';foreach($d['activity'] as $item)$activity.='<li><strong>'.self::e(str_replace(['.','_'],' ',(string)$item['action'])).'</strong><span>'.self::e((string)$item['created_at']).' UTC</span></li>';
        $capabilities=[];foreach(['coordinate'=>'Coordinate','manage_resources'=>'Manage private resources','manage_members'=>'Manage members','manage_household'=>'Govern Household'] as $cap=>$label)if($s->can((string)$a['id'],$id,$cap))$capabilities[]=$label;
        $summary='<section class="household-summary" aria-label="Household summary"><article><strong>'.count($d['members']).'</strong><span>Members</span></article><article><strong>'.count($d['events']).'</strong><span>Private events</span></article><article><strong>'.count($d['resources']).'</strong><span>Private resources</span></article><article><strong>'.count($d['mine']).'</strong><span>Need your choice</span></article></section><section class="household-role-note"><div><p class="eyebrow">Your Household role</p><h2>'.self::e(ucfirst((string)$h['membership_role'])).'</h2><p>'.self::e(implode(' · ',$capabilities)).'</p></div><p>Household coordination is private and optional. Shared responsibilities become personal Quests only after the recipient accepts.</p></section>';
        $leave=$h['membership_role']!=='owner'?'<form method="post" action="/households/'.$id.'/leave">'.$this->csrfField().'<button class="button secondary">Leave Household</button></form>':'';$body='<section class="page-heading household-heading"><div><p class="eyebrow">Household · '.self::e(ucfirst((string)$h['membership_role'])).' · '.self::e(ucfirst((string)$h['status'])).'</p><h1>'.self::e((string)$h['name']).'</h1><p>'.self::e((string)$h['summary']).'</p></div><a href="/households">All Households</a></section>'.$summary.($mine?'<section><h2>Waiting for your choice</h2><div class="grid">'.$mine.'</div></section>':'').'<section class="household-source-grid"><article class="surface"><p class="eyebrow">Gather owns event truth</p><h2>Upcoming and recent private events</h2><ul>'.($events?:'<li>No Household events yet.</li>').'</ul></article><article class="surface"><p class="eyebrow">Consent-first coordination</p><h2>Responsibilities</h2><p>'.count($d['proposals']).' proposals · '.count($d['invitations']).' pending invitations · '.count($d['resources']).' shared resources</p></article></section>'.$coord.$manage.'<section><h2>Private resources</h2><div class="grid">'.($resources?:'<article class="empty-state"><h3>No shared resources.</h3></article>').'</div></section><section><h2>Members</h2><div class="grid">'.$members.'</div></section><section class="surface household-activity"><h2>Recent Household activity</h2><ul>'.($activity?:'<li>No activity yet.</li>').'</ul></section>'.$owner.$leave;$this->page((string)$h['name'],$body);
    }

    private function create():void{$this->act(null,function($a){return (new HouseholdService($this->database))->create($a,$_POST);},'Household created.');}
    private function accept(string $token):void{$a=Security::requireAccount();try{$id=(new HouseholdService($this->database))->accept((string)$a['id'],$token);$_SESSION['flash']='Household invitation accepted.';$this->go('/households/'.$id);}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();$this->go('/households');}}
    private function update(string $id):void{$this->act($id,function($a,$h):void{(new HouseholdService($this->database))->update($a,$h,$_POST);},'Household settings saved.');}
    private function lifecycle(string $id,string $state):void{$this->act($id,function($a,$h)use($state):void{(new HouseholdService($this->database))->lifecycle($a,$h,$state);},'Household lifecycle updated.');}
    private function invite(string $id):void{$this->act($id,function($a,$h):void{(new HouseholdService($this->database))->invite($a,$h,(string)($_POST['email']??''),(string)($_POST['role']??'member'));},'Invitation queued for delivery.');}
    private function revokeInvitation(string $id,string $invitation):void{$this->act($id,function($a,$h)use($invitation):void{(new HouseholdService($this->database))->revokeInvitation($a,$h,$invitation);},'Invitation revoked.');}
    private function leave(string $id):void{$this->csrf();$a=Security::requireAccount();try{(new HouseholdService($this->database))->leave((string)$a['id'],$id);$_SESSION['flash']='You left the Household.';}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();}$this->go('/households');}
    private function role(string $id,string $member):void{$this->act($id,function($a,$h)use($member):void{(new HouseholdService($this->database))->changeRole($a,$h,$member,(string)($_POST['role']??'member'));},'Membership updated.');}
    private function remove(string $id,string $member):void{$this->act($id,function($a,$h)use($member):void{(new HouseholdService($this->database))->remove($a,$h,$member);},'Member removed.');}
    private function transfer(string $id,string $member):void{$this->act($id,function($a,$h)use($member):void{(new HouseholdService($this->database))->transfer($a,$h,$member);},'Household ownership transferred.');}
    private function resource(string $id):void{$this->act($id,function($a,$h):void{(new HouseholdService($this->database))->resource($a,$h,$_POST);},'Private resource added.');}
    private function event(string $id):void{$this->act($id,function($a,$h){return (new HouseholdService($this->database))->createEvent($a,$h,$_POST);},'Private Gather event created.');}
    private function propose(string $id):void{$this->act($id,function($a,$h):void{(new HouseholdService($this->database))->proposeQuest($a,$h,$_POST);},'Responsibility proposed for review.');}
    private function respond(string $proposal,string $response):void{$this->csrf();$a=Security::requireAccount();try{$quest=(new HouseholdService($this->database))->respond((string)$a['id'],$proposal,$response);$_SESSION['flash']=$response==='accepted'?'Responsibility accepted into your Quests.':'Responsibility declined.';$this->go($quest?'/quests/'.$quest:'/households');}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();$this->go('/households');}}
    private function act(?string $id,callable $action,string $success):void{$this->csrf();$a=Security::requireAccount();try{$result=$action((string)$a['id'],$id);$_SESSION['flash']=$success;$this->go($id?'/households/'.$id:'/households/'.$result);}catch(RuntimeException $e){$_SESSION['flash']=$e->getMessage();$this->go($id?'/households/'.$id:'/households');}}
    private function csrf():void{if(!Security::verifyCsrf((string)($_POST['csrf']??'')))throw new RuntimeException('Your session token expired.');}
    private function csrfField():string{return '<input type="hidden" name="csrf" value="'.self::e(Security::csrfToken()).'">';}
    private function missing():void{http_response_code(404);$this->page('Household unavailable','<section class="empty-state"><h1>That Household is unavailable.</h1></section>');}
    private function go(string $path):never{header('Location: '.$path,true,303);exit;}
    private function page(string $title,string $body):void{$flash='';if(isset($_SESSION['flash'])){$flash='<div class="notice" role="status">'.self::e((string)$_SESSION['flash']).'</div>';unset($_SESSION['flash']);}echo '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.self::e($title).' · Koravik</title><link rel="stylesheet" href="/assets/app.css"><link rel="stylesheet" href="/assets/journey.css"><link rel="stylesheet" href="/assets/household-dashboard.css"></head><body><main id="main" class="page">'.$flash.$body.'</main><footer>Koravik · Private Households</footer></body></html>';}
    private static function e(string $v):string{return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
}
